### ISSUE TITLE
Question about fine-tuning

### ISSUE THREAD

**Issue by hanskumarKEF** [princeton-vl/RAFT-Stereo#13]
I would like to fine-tune the pre-trained middleberry model on my own stereo data. 

I had a few questions:

a) Is this possible by simply supplying the train_stereo.py script with the --restore_ckpt param 
b) Am i able to change the default image crop size of [320, 720] for this finetuning?
c) currently i cannot train without downsampling due to a lack of memory. Since the pretrained middleberry model is not downsampled, is there anyway that i can use it for training?

Thank you so much for this work!

**Comment by lahavlipson** [comment]
a) Yes, exactly

b) Yes, just use `--image_size` (make sure it is smaller than the original image)

c) To finetune using the middlebury pre-trained weights and with `--n_downsample 3`, some of the loaded parameters will not have the correct size. You could simply not load these parameters:

Replace [Line 146 in train_stereo.py](https://github.com/princeton-vl/RAFT-Stereo/blob/main/train_stereo.py#L146) with
```
del checkpoint['module.update_block.mask.2.weight'], checkpoint['module.update_block.mask.2.bias']
model.load_state_dict(checkpoint, strict=False)
```
