### ISSUE TITLE
No such file or directory: 'datasets/flyingthings_validation.txt'

### ISSUE THREAD

**Issue by Harmon-l** [princeton-vl/RAFT-Stereo#2]
Thanks for your work! I’m studing your code, but when I try to run the [train_stereo.py](https://github.com/princeton-vl/RAFT-Stereo/blob/main/train_stereo.py), it returned an error that Cannot find the file **flyingthings_validation.txt** under datasets. I have downloaded and placed the datasets as README.md say, but I don't know where I can find the file **flyingthings_validation.txt**. Thanks for your reply.

**Comment by lahavlipson** [comment]
Sorry about that, flyingthings_validation.txt was a list of randomly chosen image pairs from the FlyingThings3D test set that I used for validation. I updated the code so this file is no longer needed.

**Comment by Harmon-l** [comment]
Oh, I see. Thank you very much for your reply. I have deleted the relevant code and now it's  running.
