### ISSUE TITLE
Problem about training

### ISSUE THREAD

**Issue by cht123456abc** [princeton-vl/RAFT-Stereo#21]
Hello, here are two questions about training. 
When I use this  <python train_stereo.py --train_datasets middlebury_Q  **--batch_size 2** --train_iters 22 --valid_iters 32  **--n_downsample 3** --num_steps 200 --mixed_precision> with a 8g memory gpu, there will be problems at some data point, as shown in the figure below：
![image](https://user-images.githubusercontent.com/29218294/150645337-b2c2bc1e-6ed2-449c-92a4-edcedea9bfc0.png)
![image](https://user-images.githubusercontent.com/29218294/150645190-e0494139-a706-4db3-b6eb-6a8783d0b4a6.png)

And another problem occurs when i use this sentence <python train_stereo.py --train_datasets middlebury_Q  **--batch_size 1** --train_iters 22 --valid_iters 32  **--n_downsample 2** --num_steps 200 --mixed_precision>,i got 
![image](https://user-images.githubusercontent.com/29218294/150645868-0d3c80cb-74fc-467c-8474-585cdb1df9e9.png)
else at some point
![image](https://user-images.githubusercontent.com/29218294/150645900-e52029a3-1369-4c09-83eb-b62cf9ce7ca0.png)

if **--batch_size is 2** and **--n_downsample is 2**,there will be no problems.
And i have to set batch_size to 1 due to my low gpu memory. 
Could you help me with this problem?Please forgive my ignorance.
Any information offered will be important.
Thanks

**Comment by lahavlipson** [comment]
These two errors look related. It appears that the image dimensions are incorrect (maybe you modified the dataloader/dataset/augmentor?). Probably the batch dimension got removed at some point. 

I can't speak to exactly why your code is only working when the batch size is > 1. However, note that the feature extractor downsamples the image by 4x, and the correlation pyramid downsamples the _width_ of the image another 8x times. If a tensor has a width of only a few pixels (i.e. the first error), downsampling further will give you a zero-width tensor.

**Comment by cht123456abc** [comment]
Thanks a lot ! 
If I replace dataset middlebury_Q with middlebury_H and set n_downsample to 3 ,the errors above will disappear.
