### ISSUE TITLE
Question on training a RAFT-Stereo model capable of handling positive and negative disparity

### ISSUE THREAD

**Issue by anandravi24** [princeton-vl/RAFT-Stereo#34]
Hello,

Amazing work on this paper! I am experimenting with RAFT-Stereo to work on stereo pairs with positive and negative disparity values. I wanted to know if raft-stereo can handle stereo pairs with positive and negative disparity. What will be the best way to train such a network? Would a dataset with positive and negative ground truth disparities values suffice or do I need to change some parts of the architecture?

**Comment by lahavlipson** [comment]
You don't need to modify any aspect of the RAFT-Stereo architecture in order to train it for both positive and negative disparities. Simply training the model on a dataset with positive and negative ground truth disparity is enough.

**Comment by anandravi24** [comment]
Thanks @lahavlipson for your quick response!
