### ISSUE TITLE
What is raftstereo-middlebury.pth trained on?

### ISSUE THREAD

**Issue by nikitakaraevv** [princeton-vl/RAFT-Stereo#38]
Hi @lahavlipson,
Thank you for your great work!

I'm wondering what datasets you used to train `raftstereo-middlebury.pth`? Why do you recommend it for in-the-wild images?

**Comment by nikitakaraevv** [comment]
Thank you!

**Comment by lahavlipson** [comment]
FYI I have just added a script to download all of the finetuning data and updated the README to specify exactly which command to run.
