### ISSUE TITLE
Question about parameters of training ETH3D

### ISSUE THREAD

**Issue by David-Zhao-1997** [princeton-vl/RAFT-Stereo#46]
In your paper, you metioned that 

> "we simulate ETH3D’s image distribution by fine tuning the network
> on additional greyscale Sceneflow images with gamma adjustment to simulate the often-overexposed black-and-white
> images in ETH3D.:

Could you please tell me how to set the greyscale and which gamma value do you use for training.

Thanks

**Comment by lahavlipson** [comment]
I set the greyscale and gamma adjustment using `--saturation_range 0 0 --img_gamma 0.5 2.0 0.8 1.2`
