### ISSUE TITLE
About the disparity range

### ISSUE THREAD

**Issue by claudio-bon** [princeton-vl/RAFT-Stereo#49]
I saw that some limitations were put in place in order to bound the maximum disparity value:
https://github.com/princeton-vl/RAFT-Stereo/blob/5899261abcf773aff652d71bf32ab62298d70add/core/stereo_datasets.py#L100
https://github.com/princeton-vl/RAFT-Stereo/blob/5899261abcf773aff652d71bf32ab62298d70add/train_stereo.py#L35
https://github.com/princeton-vl/RAFT-Stereo/blob/5899261abcf773aff652d71bf32ab62298d70add/train_stereo.py#L46
If I want to increase the maximum disparity, would increasing these constants be enough?
Moreover, is there an easy way to set a minimum disparity value?

**Comment by lahavlipson** [comment]
Yes, increasing these should be all that is necessary. To set a minimum disparity value, you can zero-out the mask at those pixels in the same way.

**Comment by claudio-bon** [comment]
Thank you for your answer.
