### ISSUE TITLE
Question about  fine-tunning on middlebury

### ISSUE THREAD

**Issue by excllent123** [princeton-vl/RAFT-Stereo#52]
Hi  
In  paper  section  4.4. Middlebury,After pre-training on Sceneflow [23], we fine-tune on 384x1000 random crops of the 23 Middlebury traning images for 4000 steps with a batch size of 2, using 22 update iterations during training
but in official_train.txt, only containt 10 Middlebury traning images ,
could you help me point out  which is right?

Thanks

**Comment by lahavlipson** [comment]
We use the 23 images w/ ground-truth in the Middlebury 2014 dataset: https://vision.middlebury.edu/stereo/data/scenes2014/

The official_train.txt corresponds to the [10 evaluation training sets with GT](https://vision.middlebury.edu/stereo/data/scenes2014/#:~:text=%C2%A0%2010%20evaluation%20training%20sets%20with%20GT)

**Comment by lahavlipson** [comment]
FYI I have just added a script to download all of the finetuning data and updated the README to specify exactly which command to run.

I'm closing this issue, feel free to reopen.
