### ISSUE TITLE
Colab or HugginFace?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [princeton-vl/RAFT-Stereo#57]
Thanks for sharing this great work!
Would you consider making a Google Colab notebook or Huggingface demo of this code so that the less technically inclined like myself can try it out?
Thanks!

**Comment by lahavlipson** [comment]
If it would be helpful, I can add a google colab notebook for RAFT-Stereo.

**Comment by noobtoob4lyfe** [comment]
That would be fantastic!

**Comment by lahavlipson** [comment]
@noobtoob4lyfe Sorry for the extremely late response!

Here is a google Colab with point cloud visualization: https://colab.research.google.com/drive/1G8WJCQt9y55qxQH6QV6PpPvWEbd393g2?usp=sharing
