### ISSUE TITLE
camera noise 

### ISSUE THREAD

**Issue by gpuartifact** [princeton-vl/RAFT-Stereo#61]
Hello,
Would you recommend to either: 
a) add the expected camera noise to the simulation data for training to implicitly train de-noise 
or
b) should the camera image be de-noised first as good as it can be before passing it to RAFT-stereo?

I am trying to train a for a specific camera sensor.

**Comment by lahavlipson** [comment]
This sounds like an empirical question. I suggest try different options and pick the model with the best validation performance.
