### ISSUE TITLE
Question about  disparity   Up &  Down

### ISSUE THREAD

**Issue by excllent123** [princeton-vl/RAFT-Stereo#64]
Hi   
I  want to compute the up-down disparity ,   and then fusion with  left-right disaprity, my  solution is 

disparity_x = RAFT_x(Img_Left, Img_Right)
disparity_y = RAFT_y(Img_Up Img_Down)
disparity_out = disparity_x * ratio_x + disparity_y * ratio_y

In RAFT_y I modify  correction function to  y-direction correction
but result is not good,could  you  give me some advice?

Thanks

**Comment by lahavlipson** [comment]
Can you clarify what are ratio_x and ratio_y? Why do you want to fuse the two disparities?

**Comment by excllent123** [comment]
ratio_x   is  confidence  of  disparity_x
because  I want to  fuse all input information
