### ISSUE TITLE
Question about Training Schedule

### ISSUE THREAD

**Issue by AbnerCSZ** [princeton-vl/RAFT-Stereo#7]
Thanks for sharing such an excellent work!  
Mentioned in the paper:  
`Final models are trained on synthetic data for 200k steps with a batch size of 8`  
SceneFlow consists of about 35k training pictures.  
Can we think that you have trained a total of 200k*8/35k ~= 45 epochs?  
GANet, DSMNet, etc. only train 10-20 epochs. Have you compared the performance when the training epoch is less than 20?  
How long does it take to train 200k Steps under your GPU configuration?  

thank you for your reply!

**Comment by lahavlipson** [comment]
It varies depending on the input size. I ran the real-time model from the README using the default pytorch implementation (`--corr_implementation reg`) and got 20.44-FPS

**Comment by AbnerCSZ** [comment]
Thank you for your answers!
