### ISSUE TITLE
The problem encountered during training with my own dataset.

### ISSUE THREAD

**Issue by zza1617** [princeton-vl/RAFT-Stereo#76]
May I ask how to fine-tune a pre-trained model using my own dataset, which includes three subfolders under a main folder, one for left views, one for right views, and another one for disparity maps? I'm not sure how to proceed with the training process, so I would appreciate any help. Thank you very much.

**Comment by zza1617** [comment]
Thanks

**Comment by zhangjy328** [comment]
Hello, have you achieved it? Can you share with me how to do it? I also want to train my own dataset, but I don't know how to deal with it.
