### ISSUE TITLE
Finetune on ETH3D

### ISSUE THREAD

**Issue by Windsrain** [princeton-vl/RAFT-Stereo#77]
Hello，Could you please tell me how to set num_steps and lr when finetuning on eth3d？I guess that I should use the pretrained model on sceneflow and retrain it with greyscale sceneflow dataset. Is it right?

**Comment by lahavlipson** [comment]
num_steps=`4000` and lr=`1e-5`

Yes, we finetuned the `raftstereo-sceneflow.pth` weights on additional greyscale sceneflow images, specifically using `--saturation_range 0 0 --img_gamma 0.5 2.0 0.8 1.2`
