### ISSUE TITLE
When I training  on my custom dataset,I get the flowing error. I want to konw what factors can cause the following error?

### ISSUE THREAD

**Issue by LaiHei** [princeton-vl/RAFT-Stereo#8]
Traceback (most recent call last):
  File "train_stereo.py", line 267, in <module>
    train(args, timestr)
  File "train_stereo.py", line 176, in train
    loss, metrics = sequence_loss(flow_predictions, flow, valid)
  File "train_stereo.py", line 53, in sequence_loss
    assert not torch.isnan(flow_preds[i]).any() and not torch.isinf(flow_preds[i]).any()
AssertionError

**Comment by lahavlipson** [comment]
NaN/Infs might occur if your learning rate is too high or you have NaN/Infs in your input. I suggest checking your loss curve to see if it is diverging. 

As far as I'm aware, there's nothing unique to RAFT-Stereo (like divisions) that could cause NaN/Infs.

**Comment by lahavlipson** [comment]
I'll close this for now - you can reopen if you need to follow up.
