### ISSUE TITLE
Questions about Table 6

### ISSUE THREAD

**Issue by AbnerCSZ** [princeton-vl/RAFT-Stereo#9]
In Table 6 of the paper, the 'Collapsed Cost Volume' experiment shows that RAFT-Stereo is faster than RAFT and has fewer parameters, but it does not provide 1px error on the FlyingThings3D dataset. Does RAFT-Stereo have an advantage over RAFT in accuracy?

Thanks!

**Comment by lahavlipson** [comment]
Regarding the 'Collapsed Cost Volume' ablation experiment, collapsing the cost volume of RAFT on its own shouldn't result in improved accuracy, hence we only report the runtime improvement in this case.

**Comment by AbnerCSZ** [comment]
thank you for your reply!
